http_addr = "[::]:9393"
grpc_addr = "[::]:9394"
offline_threshold = 30
notify_interval = 30
group_gc = 30
admin_user = ""
admin_pass = ""
# server_url = "https://yourdomain/report"
workspace = "/opt/ServerStatus"

hosts = [
  {name = "TEST1", password = "password", alias = "TEST1", location = "JP", type = "x86"},
  {name = "TEST2", password = "password", alias = "TEST2", location = "KR", type = "arm"},
]

hosts_group = [
  {gid = "Group1", password = "password", location = "CEFTA", type = "x86"},
  {gid = "Group2", password = "password", location = "CEFTA", type = "arm"},
]

[tgbot]
enabled = false
bot_token = ""
chat_id = ""
title = "<b>ServerStatus</b>"
online_tpl =  "{{config.title}} \n{{host.location}} - {{host.alias}} ({{host.name}}) Online"
offline_tpl = "{{config.title}} \n{{host.location}} - {{host.alias}} ({{host.name}}) Offline"
custom_tpl = """
"""

[log]
enabled = false
log_dir = "/opt/ServerStatus/logs"
tpl = """{% set obj = dict(event=event, host=host, ip_info=ip_info, sys_info=sys_info) %} {{ obj | tojson}}"""
